[package]
name = "algolings-cli"
version = "0.1.0"
edition = "2024"
license.workspace = true

[[bin]]
name = "algolings"
path = "src/main.rs"

[dependencies]
algolings-trace = { path = "../algolings-trace" }
crossterm = "0.29.0"
notify = "8.2.0"
ratatui = "0.30.2"
serde_json = "1.0.151"

[dev-dependencies]
tempfile = "3.27.0"
